spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: hj
    password: 1234
    dbcp2:
      test-while-idle: true
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  output:
    ansi:
      enabled: detect
  server:
    port: 8080
    servlet:
      context-path: /
      encoding:
        charset: UTF-8
        enabled: true
        force: true
    error:
      include-message: always
jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
